apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: react
  name: react
  namespace: argocd
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: multienv-nginx-react
  sessionAffinity: None
status:
  loadBalancer: {}
